export default function Head() {
  return (
    <>
      <title>Está Logado</title>
      <meta content="width:device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Alexandre Junior" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
